#!/usr/bin/env bash
# AutoCut for DaVinci Resolve - installer for macOS (Apple Silicon)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$HOME/.autocut/app"
MODEL_DIR="$HOME/.autocut/models"
MODEL_PATH="$MODEL_DIR/ggml-large-v3-turbo.bin"
MODEL_URL="https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3-turbo.bin"
PY_FW="/Library/Frameworks/Python.framework/Versions/3.12"
PY_PKG_URL="https://www.python.org/ftp/python/3.12.8/python-3.12.8-macos11.pkg"
SCRIPTS_DIR="$HOME/Library/Application Support/Blackmagic Design/DaVinci Resolve/Fusion/Scripts/Utility"

say()  { printf "\n\033[1;34m==>\033[0m %s\n" "$*"; }
warn() { printf "\n\033[1;33m!!\033[0m %s\n"  "$*"; }
die()  { printf "\n\033[1;31mXX\033[0m %s\n"  "$*"; exit 1; }

say "AutoCut installer"

# 1. macOS
[[ "$(uname)" == "Darwin" ]] || die "This installer is for macOS."

# 2. DaVinci Resolve
[[ -d "/Applications/DaVinci Resolve/DaVinci Resolve.app" ]] \
  || die "DaVinci Resolve is not installed. Get it from https://www.blackmagicdesign.com (free version is fine)."

# 3. Homebrew (needed for ffmpeg + whisper-cpp)
if ! command -v brew >/dev/null 2>&1; then
  die "Homebrew is required. Install from https://brew.sh and re-run this script."
fi

# 4. ffmpeg
if ! command -v ffmpeg >/dev/null 2>&1; then
  say "Installing ffmpeg via brew..."
  brew install ffmpeg
else
  say "ffmpeg already present."
fi

# 5. whisper-cpp (provides whisper-cli)
if ! command -v whisper-cli >/dev/null 2>&1 \
   && [[ ! -x /opt/homebrew/bin/whisper-cli ]] \
   && [[ ! -x /usr/local/bin/whisper-cli ]]; then
  say "Installing whisper.cpp via brew..."
  brew install whisper-cpp
else
  say "whisper-cli already present."
fi

# 6. python.org Python 3.12 framework (Resolve scans for .py only when this exists)
if [[ ! -d "$PY_FW" ]]; then
  warn "python.org Python 3.12 is missing -- Resolve will not show .py scripts without it."
  PKG="$HOME/Downloads/python-3.12.8-macos11.pkg"
  if [[ ! -f "$PKG" ]]; then
    say "Downloading python.org 3.12.8 (~45 MB)..."
    curl -fL --progress-bar -o "$PKG" "$PY_PKG_URL"
  fi
  echo
  echo "Please install Python 3.12 now -- run this command in a Terminal:"
  echo
  echo "    sudo installer -pkg \"$PKG\" -target /"
  echo
  echo "(or double-click the .pkg in ~/Downloads), then re-run this installer."
  exit 1
else
  say "python.org Python 3.12 framework present."
fi

# 7. whisper model -- reuse any copy already on disk before downloading 1.5 GB.
mkdir -p "$MODEL_DIR"
KNOWN_MODELS=(
  "$MODEL_PATH"
  "$HOME/Library/Application Support/vowen/models/ggml-large-v3-turbo.bin"
  "$HOME/Library/Caches/whisper.cpp/ggml-large-v3-turbo.bin"
  "/opt/homebrew/share/whisper.cpp/ggml-large-v3-turbo.bin"
)
FOUND_MODEL=""
for m in "${KNOWN_MODELS[@]}"; do
  if [[ -f "$m" ]]; then FOUND_MODEL="$m"; break; fi
done

if [[ -f "$MODEL_PATH" ]]; then
  say "Whisper model already at $MODEL_PATH."
elif [[ -n "$FOUND_MODEL" ]]; then
  say "Found existing model at $FOUND_MODEL -- linking it (no re-download)."
  ln -sf "$FOUND_MODEL" "$MODEL_PATH"
else
  say "Downloading ggml-large-v3-turbo model (~1.5 GB, one-time)..."
  curl -fL --progress-bar -o "$MODEL_PATH" "$MODEL_URL"
fi

# 8. Project code (core + docs so the in-app Help can show its image)
say "Copying AutoCut code to $APP_DIR..."
mkdir -p "$APP_DIR"
rm -rf "$APP_DIR/core" "$APP_DIR/docs"
cp -R "$SCRIPT_DIR/core" "$APP_DIR/core"
cp -R "$SCRIPT_DIR/docs" "$APP_DIR/docs"

# 9. Resolve Scripts launcher
say "Installing launcher into Resolve Scripts > Utility..."
mkdir -p "$SCRIPTS_DIR"
cat > "$SCRIPTS_DIR/AutoCut Panel.py" <<'PY'
# Auto-generated by AutoCut installer.
import os
import sys

PROJECT_CORE = os.path.expanduser("~/.autocut/app/core")
if PROJECT_CORE not in sys.path:
    sys.path.insert(0, PROJECT_CORE)

for _name in ("ui", "engine", "captions", "transcribe", "srt", "silence",
              "fillers", "repeats", "intervals", "clips", "resolve_connect", "ai"):
    sys.modules.pop(_name, None)

import ui  # noqa: E402

_resolve = globals().get("resolve")

print("=== AutoCut Panel ===")
try:
    ui.run(resolve_app=_resolve)
except Exception as exc:
    print(f"AutoCut Panel error: {exc}")
    import traceback
    traceback.print_exc()
PY

cat <<EOF

\033[1;32mAll set!\033[0m
   1. Quit DaVinci Resolve (Cmd+Q) and reopen it.
   2. Workspace > Scripts > Utility > "AutoCut Panel".

If the menu item is missing, double-check the Python 3.12 framework is installed.
EOF
